### ISSUE TITLE
OpenCV versions Conflict 

### ISSUE THREAD

**Issue by bwajster97** [lanzani/jetson-docs#2]
Prior to following the steps on the link: https://jetson-docs.com/libraries/opencv/l4t32.7.1/py3.6.9 I had OpenCV 4.1.2 installed on my system with Cuda support. After implementing all the steps on the same link and after running the command `opencv_version ` I get 4.8.0 

But when I run `python3 -c "import cv2; print(cv2.__version__)"` or Step7 of the link above `python3 -c "import cv2; print('OpenCV version:', str(cv2.__version__)); print(cv2.getBuildInformation())"` I get OpenCV version: 4.1.2 and it's build details. I need to see OpenCV version as 4.8.0 after running the command  `python3 -c "import cv2; print('OpenCV version:', str(cv2.__version__)); print(cv2.getBuildInformation())" ` How do I do this?

Please refer to the image attached in my next comment.

Kindly pls help.

**Comment by bwajster97** [comment]
![opencv_conflict](https://github.com/lanzani/jetson-docs/assets/75673322/ddd59e37-e33d-4ba7-b0bc-b89e1378f90f)

Pls refer to this image.

**Comment by bwajster97** [comment]
[Codes_for_Module_15.zip](https://github.com/lanzani/jetson-docs/files/13828706/Codes_for_Module_15.zip)
![opencv_conflict1](https://github.com/lanzani/jetson-docs/assets/75673322/2b1083ec-0062-4b91-8c46-62da2e34adb0)
![opencv_conflict2](https://github.com/lanzani/jetson-docs/assets/75673322/197d40a2-8348-4d42-be97-f8b906963f69)

How do I make sure python3 uses OpenCV 4.8.0 and not 4.1.2 ?

**Comment by lanzani** [comment]
Hi! This means you are almost done, have you completed all the steps form https://jetson-docs.com/libraries/opencv/l4t32.7.1/py3.6.9#install-opencv-from-package? 

From what I see, I suppose you missed step 5

**Comment by bwajster97** [comment]
![step5](https://github.com/lanzani/jetson-docs/assets/75673322/a2dca528-6072-4e3c-af4f-71a9e7575fcc)
I implemented step5. Hope it's correct, is the + sign needed at the start of the line?

**Comment by lanzani** [comment]
No, the "+" sign is not needed, try to remove it.

**Comment by bwajster97** [comment]
Here's what I'm having an issue with:
![opencv_conflict1](https://github.com/lanzani/jetson-docs/assets/75673322/a1bca1c4-cceb-405e-8c45-b52711e0d226)
![opencv_conflict2](https://github.com/lanzani/jetson-docs/assets/75673322/b6036da8-c42d-4b7d-8b14-1c75cdc4bff1)

Python3 uses 4.1.2 and not 4.8.0 
How do I ensure python3 uses 4.8.0?

**Comment by lanzani** [comment]
Run this command:
```bash
export PYTHONPATH=/usr/local/lib/python3.6/site-packages:$PYTHONPATH
```

And try again.

**Comment by bwajster97** [comment]
Do i run the command `export PYTHONPATH=/usr/local/lib/python3.6/site-packages:$PYTHONPATH` on the terminal?

**Comment by lanzani** [comment]
yes

**Comment by bwajster97** [comment]
`python -c "import cv2; print(cv2.__version__)" ` returns 4.8.0 

Thanks a ton.

**Comment by lanzani** [comment]
You are welcome, make sure you have removed the "+" sign from `.bashrc` and you are good to go :)

**Comment by bwajster97** [comment]
Running `sudo apt-get update && apt-get upgrade` gives me this:

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

Can I overlook/ignore them?

**Comment by lanzani** [comment]
Oh, sorry, I've missed a `sudo`.
The correct command is:
```bash
sudo apt-get update && sudo apt-get upgrade
```

**Comment by bwajster97** [comment]
Thank You.

**Comment by bwajster97** [comment]
It's has been 3hours since I started installing MediaPipe 0.8.5 and I'm still at:

Building wheel for opencv-contrib-python (pyproject.toml): 

What do I do?
