### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by bwajster97** [lanzani/jetson-docs#3]
After running the command` pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl` and waiting for more than 3 hours I got the error below: 
~/mediapipe-bin$ pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Processing ./v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl
Requirement already satisfied: numpy==1.19.4 in /usr/local/lib/python3.6/dist-packages (from mediapipe==0.8.5-cuda102) (1.19.4)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from mediapipe==0.8.5-cuda102) (0.30.0)
Collecting opencv-contrib-python
  Downloading opencv-contrib-python-4.9.0.80.tar.gz (152.6 MB)
     |████████████████████████████████| 152.6 MB 6.5 kB/s             
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting absl-py
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 5.2 MB/s            
Requirement already satisfied: protobuf>=3.11.4 in /usr/local/lib/python3.6/dist-packages (from mediapipe==0.8.5-cuda102) (3.19.6)
Collecting attrs>=19.1.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 2.0 MB/s            
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from mediapipe==0.8.5-cuda102) (1.11.0)
Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (pyproject.toml) ... done
  Created wheel for opencv-contrib-python: filename=opencv_contrib_python-4.9.0.80-cp36-cp36m-linux_aarch64.whl size=21413170 sha256=fe83dc36fd60abf1d280846d24af33f6fe4392f45cfa92223fa78d745e09af62
  Stored in directory: /home/nikhil/.cache/pip/wheels/d3/15/23/dafe20985a737773ed2f139e6917ecabc74d64cf17cfef1907
Successfully built opencv-contrib-python
Installing collected packages: opencv-contrib-python, attrs, absl-py, mediapipe
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/nikhil/.local/lib/python3.6'
Check the permissions.

Please help me resolve this error.

**Comment by bwajster97** [comment]
Do i need to use `sudo` or/and `-H` flag while running the command: `pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl` ?? 
Please help.

**Comment by bwajster97** [comment]
When I tried the command `pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl` with a `sudo` I got the warning below:
sudo pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl
[sudo] password for nikhil: 
WARNING: The directory '/home/nikhil/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

**Comment by bwajster97** [comment]
So  taking into consideration the above errors and warnings what's the right way to run the command `pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl` ?

**Comment by lanzani** [comment]
Hi! The fact that it takes hours is right, or at least is what I also experenced.

The command should be run with sudo:
```bash
sudo pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl
```

I also got the warning, but it don't stop the installation process, try to run the above command and ignore the warning.

**Comment by bwajster97** [comment]
Using a -H flag help avaid the warning:
`sudo -H pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl`

**Comment by bwajster97** [comment]
Does the last command` pip3 install dataclasses` need a sudo too ?

**Comment by bwajster97** [comment]
Also, are there other ways to check if MediaPipe uses the GPU? Apart from seeing log-Created TensorFlow Lite XNNPACK delegate for GPU printed in the terminal?

**Comment by lanzani** [comment]
> Does the last command` pip3 install dataclasses` need a sudo too ?

Try using sudo

**Comment by lanzani** [comment]
> Also, are there other ways to check if MediaPipe uses the GPU? Apart from seeing log-Created TensorFlow Lite XNNPACK delegate for GPU printed in the terminal?

Do you get that message?

**Comment by lanzani** [comment]
You can test it using [this](https://jetson-docs.com/libraries/mediapipe/overview#mediapipe-0-8-x) script, or one of your own and see if the framerate is accettable. 

With the script above, I got around 20 fps with a HD webcam.

**Comment by bwajster97** [comment]
Ok, thank you.

**Comment by lanzani** [comment]
Let me know if it works for you :)

**Comment by bwajster97** [comment]
Sure, I'll keep you posted.

**Comment by bwajster97** [comment]
After running the command `sudo -H pip3 install v0.8.5/v0.8.5/numpy119x/py36/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64.whl` here's what I got:
![mediapipe](https://github.com/lanzani/jetson-docs/assets/75673322/2a83cd8e-463c-4a14-8f73-de5698617b70)

And after running the pose estimation script, here's what I got:
![script](https://github.com/lanzani/jetson-docs/assets/75673322/5e4255c2-10e4-4b66-ac5b-e9b698930c55)
On hthe pic above I've highlighted the line:Created TensorFlow Lite delegate for GPU. But, on your site to validate GPU support the log is different: Created TensorFlow Lite XNNPACK delegate for GPU. 

Please confirm if 1. MediaPipe is installed successfully and 2. If the script runs with GPU support.

**Comment by lanzani** [comment]
According to your screenshots, you have mediapipe correctly installed, so:
1. Yes
2. Yes

On my website there is written: `Created TensorFlow Lite XNNPACK delegate for GPU` because maybe I copied and pasted the message from another version of mediapipe. But according to your screenshot, I can say that you installed everything successfully :)

**Comment by bwajster97** [comment]
Great, a big thank you for having the instructions and steps explained so clearly on your website, I couldn't have done it without your efforts.

**Comment by lanzani** [comment]
Thank you very much!
If you want to, leave a star to this repository :)
