### ISSUE TITLE
`l4t32.7.1-py3.8.0-ocv4.8.0-build` image doesn't work

### ISSUE THREAD

**Issue by JTShuai** [lanzani/jetson-docs#7]
Hello,

I'm using the docker image `l4t32.7.1-py3.8.0-ocv4.8.0-build` and have added `export PYTHONPATH=/usr/local/lib/python3.6/site-packages:$PYTHONPATH` in my `.bashrc` file and `source ~/.bashrc`.

1. When I ran `opencv_version`, I got the correct result: `4.8.0`
2. When I ran `python3 -c "import cv2; print('OpenCV version:', str(cv2.__version__)); print(cv2.getBuildInformation())"`, I got the error:
```
OpenCV bindings requires "numpy" package.
Install it via command:
    pip install numpy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 11, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```
**But the `numpy` has been installed**, I tested with `python3.8 -m pip install numpy==1.19.4`, and got `Requirement already satisfied: numpy==1.19.4 in /usr/local/lib/python3.8/dist-packages`.

Is there any steps I have missed to use this image? Thx!

**Comment by JTShuai** [comment]
fixed by changing the default python3 symbolic link.

**Comment by lanzani** [comment]
Great! If you want, you can add it in the docs :)
